import _Backoff from '../lib/backoff.js';
import _Cancel from '../lib/cancel.js';
import _chai from 'isotropic-dev-dependencies/lib/chai.js';
import _characterFold from '../lib/character-fold.js';
import _ClusterPrimary from '../lib/cluster-primary.js';
import _ClusterWorker from '../lib/cluster-worker.js';
import _console from '../lib/console.js';
import _create from '../lib/create.js';
import _durationToString from '../lib/duration-to-string.js';
import _Error from '../lib/error.js';
import _forIn from '../lib/for-in.js';
import _Initializable from '../lib/initializable.js';
import _instanceOf from '../lib/instance-of.js';
import _later from '../lib/later.js';
import _Lexer from '../lib/lexer.js';
import _logger from '../lib/logger.js';
import _LoggerPretty from '../lib/logger-pretty.js';
import _make from '../lib/make.js';
import _mixin from '../lib/mixin.js';
import _mixinPrototypeChain from '../lib/mixin-prototype-chain.js';
import _Mutex from '../lib/mutex.js';
import _naturalSort from '../lib/natural-sort.js';
import _PropertyChainer from '../lib/property-chainer.js';
import _prototypeChain from '../lib/prototype-chain.js';
import _Pubsub from '../lib/pubsub.js';
import _request from '../lib/request.js';
import _State from '../lib/state.js';
import _StateContext from '../lib/state-context.js';
import _TemporalFormat from '../lib/temporal-format.js';
import _test from 'node:test';
import _throttle from '../lib/throttle.js';
import _timeout from '../lib/timeout.js';
import _TimeoutCancel from '../lib/timeout-cancel.js';
import _valueToSource from '../lib/value-to-source.js';

_test.describe('isotropic', () => {
    _test.it('should export all isotropic APIs', () => {
        _chai.expect(_Backoff).to.be.an('function');
        _chai.expect(_Cancel).to.be.a('function');
        _chai.expect(_characterFold).to.be.a('function');
        _chai.expect(_ClusterPrimary).to.be.an('function');
        _chai.expect(_ClusterWorker).to.be.an('function');
        _chai.expect(typeof _console).to.equal('object');
        _chai.expect(_console).to.have.property('log').that.is.a('function');
        _chai.expect(_create).to.be.a('function');
        _chai.expect(_durationToString).to.be.a('function');
        _chai.expect(_Error).to.be.a('function');
        _chai.expect(_forIn).to.be.a('function');
        _chai.expect(_Initializable).to.be.a('function');
        _chai.expect(_instanceOf).to.be.a('function');
        _chai.expect(_later).to.be.a('function');
        _chai.expect(_later).to.have.property('asap').that.is.a('function');
        _chai.expect(_later).to.have.property('soon').that.is.a('function');
        _chai.expect(_Lexer).to.be.an('function');
        _chai.expect(typeof _logger).to.equal('object');
        _chai.expect(_LoggerPretty).to.be.a('function');
        _chai.expect(_make).to.be.a('function');
        _chai.expect(_mixin).to.be.a('function');
        _chai.expect(_mixinPrototypeChain).to.be.an('object');
        _chai.expect(_Mutex).to.be.an('function');
        _chai.expect(_naturalSort).to.be.a('function');
        _chai.expect(_PropertyChainer).to.be.a('function');
        _chai.expect(_prototypeChain).to.be.a('function');
        _chai.expect(_Pubsub).to.be.a('function');
        _chai.expect(_request).to.be.a('function');
        _chai.expect(_State).to.be.a('function');
        _chai.expect(_StateContext).to.be.a('function');
        _chai.expect(_TemporalFormat).to.be.a('function');
        _chai.expect(_TemporalFormat).to.have.property('fromString').that.is.a('function');
        _chai.expect(_TemporalFormat).to.have.property('toString').that.is.a('function');
        _chai.expect(_timeout).to.be.a('function');
        _chai.expect(_TimeoutCancel).to.be.a('function');
        _chai.expect(_throttle).to.be.a('function');
        _chai.expect(_valueToSource).to.be.a('function');
    });
});
